# CrazySpawner config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazySpawner/src/config.yml
version: X.Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazySpawner/src/plugin.yml
# the chat header used ingame (this cannot be changed via any kind of reload)
chatHeader: '&C[&ACrazySpawner&C] &F'
# If a mob is attacked every mob within the given radius will loose its peaceful state.
defaultAlarmRange: 10.0
# If false every explosion damage (except tnt) is blocked for hostile mobs.
# Example: Creeper won't kill other creepers.
monsterExplosionDamageEnabled: true
# All custom creatures have to be defined here
creatures: {}
# All spawn task are defined here
tasks: {}
