# CrazySpawner config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazySpawner/src/config.yml
version: X.Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazySpawner/src/plugin.yml
# the chat header used ingame (this cannot be changed via any kind of reload)
chatHeader: '&C[&ACrazySpawner&C] &F'
# All custom creatures have to be defined here
creatures: {}
# All spawn task are defined here
tasks: {}
