name: CrazySpawner
main: de.st_ddt.crazyspawner.CrazySpawner
author: ST-DDT
version: 4.3
website: http://dev.bukkit.org/server-mods/crazyspawner/
# requires CrazyCore v10.7.6 or later
depend: [CrazyCore]
description: >
            CrazySpawner spawn and remove mobs where ever you like.
commands:
  crazyspawn:
    description: Spawn living Creatures...
    usage: /<command> <creature:Creature> [amount:Integer] [repeat:Integer] [interval:Duration] [delay:Duration] [synced:Boolean] [chunkloadrange:Integer] [creaturemaxcount:Integer [creaturerange:Double]] [playermincount:Integer [playerrange:Double]] [blockingrange:Double] [allowdespawning:Boolean] [peaceful:Boolean] [location:Location] [health:Integer] [showHealth:Boolean]
    aliases: [crazymobs, cms, spawnmob]
  crazykill:
    description: Kill living Creatures...
    usage: /<command> <Range> [monster:Boolean] [animals:Boolean] [golems:Boolean] [villagers:Boolean] [bosses:Boolean] [location:Location]
    aliases: [butcher, killall, cmk, killmob]
  crazycreaturespawner:
    description: Change spawner types.
    usage: /<command> <Creature>
    aliases: [spawner, creaturespawner, ccs]
  crazytheendautorespawn:
    description: Create auto respawn tasks for EnderDragons and EnderCrystals.
    usage: /<command> [interval:Duration] [world:World] [chunkloadrange:Integer]
    aliases: [theendautorespawn, ctearespawn, tearespawn,ctear,tear]
  mountme:
    description: Spawn an entity and ride it.
    usage: /<command> <entity:NamedEntityType> [player:Player]
    aliases: [mount,ride]
  crazyspawner:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
    aliases: [cspawner]
permissions:
  crazyspawner.*:
    description: Access to all permissions belonging to this plugin.
    default: op
    children:
      crazycore.protectedplayer: true
      crazyspawner.creaturespawner: true
      crazyspawner.creaturespawner.*: true
      crazyspawner.help: true
      crazyspawner.info: true
      crazyspawner.kill: true
      crazyspawner.list: true
      crazyspawner.logger: true
      crazyspawner.mode: true
      crazyspawner.mode.*: true
      crazyspawner.mode.defaultalarmrange: true
      crazyspawner.mode.monsterexplosiondamageenabled: true
      crazyspawner.modifyentity: true
      crazyspawner.mountme: true
      crazyspawner.mountme.*: true
      crazyspawner.mountme.others: true
      crazyspawner.mountme.self: true
      crazyspawner.overwriteentity: true
      crazyspawner.reload: true
      crazyspawner.reload.*: true
      crazyspawner.reload.config: true
      crazyspawner.reload.entities: true
      crazyspawner.reload.spawntasks: true
      crazyspawner.remove: true
      crazyspawner.save: true
      crazyspawner.showentity: true
      crazyspawner.spawn: true
      crazyspawner.spawn.*: true
      crazyspawner.theendautorespawn: true
  crazyspawner.creaturespawner:
    description: Allow changing of creature spawners.
    default: op
  crazyspawner.creaturespawner.*:
    description: Allow changing of creature spawners to all possible types.
    default: op
  crazyspawner.help:
    description: Allow accessing the plugin help.
    default: op
  crazyspawner.info:
    description: Allow showing information about this plugin.
    default: op
  crazyspawner.kill:
    description: Allow killing of creatures.
    default: op
  crazyspawner.list:
    description: Allow removing spawn tasks.
    default: op
  crazyspawner.logger:
    description: Allow configuring the plugin logger.
    default: op
  crazyspawner.mode:
    description: Allow changing plugin modes.
    default: op
  crazyspawner.mode.*:
    description: Allow changing all plugin modes.
    default: op
  crazyspawner.mode.defaultalarmrange:
    description: Allow changing defaultAlarmRange mode.
    default: op
  crazyspawner.mode.monsterexplosiondamageenabled:
    description: Allow changing monsterExplosionDamageEnabled mode.
    default: op
  crazyspawner.modifyentity:
    description: Allow creating/modifing of custom entities.
    default: op
  crazyspawner.mountme:
    description: Allow spawning of entities and ride it.
    default: op
  crazyspawner.mountme.*:
    description: Allow spawning all possible entities and ride them.
    default: op
  crazyspawner.mountme.others:
    description: Allow spawning of entities for others players and let him ride it.
    default: op
    children:
      crazyspawner.mountme: true
  crazyspawner.mountme.self:
    description: Allow spawning of entities for yourself and ride it.
    default: op
    children:
      crazyspawner.mountme: true
  crazyspawner.overwriteentity:
    description: Allow overwriting default entities.
    default: op
  crazyspawner.reload:
    description: Allow accessing the reload command.
    default: op
  crazyspawner.reload.*:
    description: Allow reloading the entire plugin.
    default: op
    children:
      crazyspawner.reload.config: true
      crazyspawner.reload.entities: true
      crazyspawner.reload.spawntasks: true
  crazyspawner.reload.config:
    description: Allow reloading the config.
    default: op
  crazyspawner.reload.entities:
    description: Allow reloading the custom entities.
    default: op
  crazyspawner.reload.spawntasks:
    description: Allow reloading the spawn tasks.
    default: op
  crazyspawner.remove:
    description: Allow removing of spawn tasks.
    default: op
  crazyspawner.save:
    description: Allow saving the plugin.
    default: op
  crazyspawner.showentity:
    description: Allow displaying of custom entity properties.
    default: op
  crazyspawner.spawn:
    description: Allow spawning of entities.
    default: op
  crazyspawner.spawn.*:
    description: Allow spawning of all possible entities.
    default: op
  crazyspawner.theendautorespawn:
    description: Allow creating auto respawn tasks for EnderDragons and EnderCrystals.
    default: op