name: CrazySpawner
main: de.st_ddt.crazyspawner.CrazySpawner
author: ST-DDT
version: 3.1
# requires CrazyCore v9.0.7 or later
depend: [CrazyCore]
description: >
            CrazySpawner spawn and remove mobs where ever you like.
commands:
  crazyspawn:
    description: Spawn living Creatures...
    usage: /<command> <Monstername> [amount:Integer] [delay:Integer] [repeat:Integer] [interval:Integer] [monstermaxcount:Integer [monsterradius:Double]] [playermincount:Integer [playerradius:Double]]
    aliases: [spawn,crazymobs, cms]
  crazykill:
    description: Kill living Creatures...
    usage: /<command> <Range> [monster:Boolean] [animals:Boolean] [golems:Boolean] [villagers:Boolean] [bosses:Boolean]
    aliases: [butcher,killall,cmk]
  crazyspawner:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
permissions:
  crazyspawner.*:
    description: Access to all commands
    default: false
    children:
      crazyspawner.spawn: true
      crazyspawner.kill: true
  crazyspawner.spawn:
    description: Allow spawning of Creatures
    default: op
  crazyspawner.kill:
    description: Allow killing of Creatures
    default: op