name: CrazySpawner
main: de.st_ddt.crazyspawner.CrazySpawner
author: ST-DDT
version: 3.2
# requires CrazyCore v9.2 or later
depend: [CrazyCore]
description: >
            CrazySpawner spawn and remove mobs where ever you like.
commands:
  crazyspawn:
    description: Spawn living Creatures...
    usage: /<command> <Creature> [amount:Integer] [delay:Duration] [repeat:Integer] [interval:Duration] [monstermaxcount:Integer [monsterradius:Double]] [playermincount:Integer [playerradius:Double]] [location:Location]
    aliases: [spawn,crazymobs, cms]
  crazykill:
    description: Kill living Creatures...
    usage: /<command> <Range> [monster:Boolean] [animals:Boolean] [golems:Boolean] [villagers:Boolean] [bosses:Boolean] [location:Location]
    aliases: [butcher,killall,cmk]
  crazycreaturespawner:
    description: Change spawner types.
    usage: /<command> <Creature>
    aliases: [spawner,crazyspawner,ccs]
  crazyspawner:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
permissions:
  crazyspawner.*:
    description: Access to all commands
    default: false
    children:
      crazyspawner.spawn: true
      crazyspawner.kill: true
  crazyspawner.spawn:
    description: Allow spawning of Creatures
    default: op
  crazyspawner.kill:
    description: Allow killing of Creatures
    default: op